/*
Copyright 2023 Stefan Prodan

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path"
	"sort"
	"strings"

	"cuelang.org/go/cue/cuecontext"
	ssautil "github.com/fluxcd/pkg/ssa/utils"
	"github.com/go-logr/logr"
	"github.com/hashicorp/go-cleanhttp"
	"github.com/spf13/cobra"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/yaml"

	"github.com/stefanprodan/timoni/internal/engine"
	"github.com/stefanprodan/timoni/internal/logger"
)

var vendorCrdCmd = &cobra.Command{
	Use:     "crd [MODULE PATH]",
	Args:    cobra.MaximumNArgs(1),
	Aliases: []string{"crds"},
	Short:   "Vendor Kubernetes CRD CUE schemas",
	Example: `  # Vendor CUE schemas generated from Kubernetes CRDs included in a local YAML file
  timoni mod vendor crd -f crds.yaml

  # Vendor CUE schemas generated from Kubernetes CRDs included in a remote YAML file
  timoni mod vendor crd -f https://github.com/fluxcd/flux2/releases/latest/download/install.yaml

  # List the CRD kinds and versions found in a YAML file without vendoring them
  timoni mod vendor crd -f crds.yaml --list

  # Vendor only the selected kinds and versions
  timoni mod vendor crd -f crds.yaml --kind HTTPRoute,Gateway.gateway.networking.k8s.io --version v1

  # Vendor the selected kinds and remove the previously vendored definitions
  # of the API groups in the YAML file that are no longer selected
  timoni mod vendor crd -f crds.yaml --kind HTTPRoute --prune
`,
	RunE: runVendorCrdCmd,
}

type vendorCrdFlags struct {
	modRoot  string
	crdFile  string
	kinds    []string
	versions []string
	list     bool
	prune    bool
}

var vendorCrdArgs vendorCrdFlags

const maxRemoteCRDManifestSize int64 = 16 << 20

func init() {
	vendorCrdCmd.Flags().StringVarP(&vendorCrdArgs.crdFile, "file", "f", "",
		"The path to Kubernetes CRD YAML.")
	vendorCrdCmd.Flags().StringSliceVar(&vendorCrdArgs.kinds, "kind", nil,
		"The CRD kinds to vendor, as Kind or Kind.group, matched case-insensitively. Defaults to all kinds.")
	vendorCrdCmd.Flags().StringSliceVarP(&vendorCrdArgs.versions, "version", "v", nil,
		"The CRD versions to vendor, matched case-insensitively. Defaults to all versions.")
	vendorCrdCmd.Flags().BoolVar(&vendorCrdArgs.list, "list", false,
		"List the CRD kinds and versions found in the YAML without vendoring them.")
	vendorCrdCmd.Flags().BoolVar(&vendorCrdArgs.prune, "prune", false,
		"Remove the previously vendored definitions of the API groups in the YAML that are not generated by this run.")
	modVendorCmd.AddCommand(vendorCrdCmd)
}

// generatedMarker is the first line of every CUE file written by the vendor commands.
const generatedMarker = "// Code generated by timoni. DO NOT EDIT."

const header = generatedMarker + `

//timoni:generate timoni mod vendor crd -f `

// crdEntry is a CustomResourceDefinition extracted from a manifest
// along with the versions it defines.
type crdEntry struct {
	kind     string
	group    string
	versions []string
	object   *unstructured.Unstructured
}

// name returns the fully qualified Kind.group of the CRD.
func (c crdEntry) name() string {
	return c.kind + "." + c.group
}

// runVendorCrdCmd vendors CUE schemas from local or remote CRD manifests.
func runVendorCrdCmd(cmd *cobra.Command, args []string) error {
	if len(args) > 0 {
		vendorCrdArgs.modRoot = args[0]
	}

	if vendorCrdArgs.list && vendorCrdArgs.prune {
		return errors.New("--list and --prune are mutually exclusive")
	}

	log := LoggerFrom(cmd.Context())
	cuectx := cuecontext.New()

	// Make sure we're importing into a CUE module.
	cueModDir := path.Join(vendorCrdArgs.modRoot, "cue.mod")
	if !vendorCrdArgs.list {
		if fs, err := os.Stat(cueModDir); err != nil || !fs.IsDir() {
			return fmt.Errorf("cue.mod not found in the module path %s", vendorCrdArgs.modRoot)
		}
	}

	spin := logger.StartSpinner("importing schemas")
	defer spin.Stop()

	crdData, err := readCRDManifest(cmd.Context(), vendorCrdArgs.crdFile)
	if err != nil {
		return err
	}

	// Extract the Kubernetes CRDs from the multi-doc YAML.
	crds, err := extractCRDs(crdData)
	if err != nil {
		return err
	}
	if len(crds) == 0 {
		return fmt.Errorf("no CRDs found in %s", vendorCrdArgs.crdFile)
	}

	// Keep only the kinds and versions selected by the user.
	selected, err := selectCRDs(crds, vendorCrdArgs.kinds, vendorCrdArgs.versions, vendorCrdArgs.crdFile)
	if err != nil {
		return err
	}

	if vendorCrdArgs.list {
		spin.Stop()
		listCRDs(cmd.OutOrStdout(), selected)
		return nil
	}

	var builder strings.Builder
	for _, crd := range selected {
		builder.WriteString("---\n")
		data, err := yaml.Marshal(crd.object)
		if err != nil {
			return fmt.Errorf("marshaling CRD failed: %w", err)
		}
		builder.Write(data)
	}

	// Generate the CUE definitions from the given CRD YAML.
	imp := engine.NewImporter(cuectx, header+vendorCrdGenerateArgs(vendorCrdArgs))
	generated, err := imp.Generate([]byte(builder.String()))
	if err != nil {
		return err
	}

	// Sort the resulting definitions based on file names.
	keys := make([]string, 0, len(generated))
	for k := range generated {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	spin.Stop()

	// Write the definitions to the module's 'cue.mod/gen' dir.
	genDir := path.Join(cueModDir, "gen")
	for _, k := range keys {
		log.Info(fmt.Sprintf("schemas vendored: %s", logger.ColorizeSubject(k)))

		dstDir := path.Join(genDir, k)
		if err := os.MkdirAll(dstDir, os.ModePerm); err != nil {
			return err
		}

		if err := os.WriteFile(path.Join(dstDir, "types_gen.cue"), generated[k], 0644); err != nil {
			return err
		}
	}

	if vendorCrdArgs.prune {
		return pruneCRDs(log, genDir, crdGroups(crds), generated)
	}

	return nil
}

// vendorCrdGenerateArgs returns the arguments recorded in the generate
// directive of the vendored files, so that re-running the directive
// reproduces the same selection of kinds and versions.
func vendorCrdGenerateArgs(flags vendorCrdFlags) string {
	genArgs := flags.crdFile
	if kinds := joinSelectors(flags.kinds); kinds != "" {
		genArgs += " --kind " + kinds
	}
	if versions := joinSelectors(flags.versions); versions != "" {
		genArgs += " --version " + versions
	}
	return genArgs
}

// joinSelectors joins the selector values given by the user, trimming whitespace.
func joinSelectors(values []string) string {
	out := make([]string, 0, len(values))
	for _, v := range values {
		out = append(out, strings.TrimSpace(v))
	}
	return strings.Join(out, ",")
}

// readCRDManifest loads the CRD YAML into memory either from disk
// or by fetching the file over HTTPS.
func readCRDManifest(ctx context.Context, file string) ([]byte, error) {
	if strings.HasPrefix(file, "https://") {
		hctx, cancel := context.WithTimeout(ctx, rootArgs.timeout)
		defer cancel()

		return readRemoteCRDManifest(hctx, cleanhttp.DefaultClient(), file, maxRemoteCRDManifestSize)
	}

	if fs, err := os.Stat(file); err != nil || !fs.Mode().IsRegular() {
		return nil, fmt.Errorf("path not found: %s", file)
	}

	return os.ReadFile(file)
}

// extractCRDs parses a multi-doc YAML and returns the CustomResourceDefinitions
// found in it, preserving the manifest order. The singular name defaults to the
// lowercase kind when not set, as the Kubernetes API server does.
func extractCRDs(crdData []byte) ([]crdEntry, error) {
	objects, err := ssautil.ReadObjects(bytes.NewReader(crdData))
	if err != nil {
		return nil, fmt.Errorf("parsing CRDs failed: %w", err)
	}

	var crds []crdEntry
	for _, object := range objects {
		if !engine.IsCRD(object) {
			continue
		}

		kind, _, _ := unstructured.NestedString(object.Object, "spec", "names", "kind")
		group, _, _ := unstructured.NestedString(object.Object, "spec", "group")
		if kind == "" || group == "" {
			return nil, fmt.Errorf("CRD %s is missing the kind or group", object.GetName())
		}
		if !isPathSegment(group) {
			return nil, fmt.Errorf("CRD %s has an invalid group %q", object.GetName(), group)
		}

		singular, _, _ := unstructured.NestedString(object.Object, "spec", "names", "singular")
		if singular == "" {
			singular = strings.ToLower(kind)
			if err := unstructured.SetNestedField(object.Object, singular, "spec", "names", "singular"); err != nil {
				return nil, fmt.Errorf("defaulting the singular name of CRD %s failed: %w", object.GetName(), err)
			}
		}
		if !isPathSegment(singular) {
			return nil, fmt.Errorf("CRD %s has an invalid singular name %q", object.GetName(), singular)
		}

		versions, _, _ := unstructured.NestedSlice(object.Object, "spec", "versions")
		entry := crdEntry{kind: kind, group: group, object: object}
		for _, v := range versions {
			version, ok := v.(map[string]any)
			if !ok {
				continue
			}
			name, _ := version["name"].(string)
			if name == "" {
				continue
			}
			if !isPathSegment(name) {
				return nil, fmt.Errorf("CRD %s has an invalid version name %q", object.GetName(), name)
			}
			entry.versions = append(entry.versions, name)
		}
		if len(entry.versions) == 0 {
			return nil, fmt.Errorf("CRD %s defines no versions", object.GetName())
		}
		crds = append(crds, entry)
	}

	return crds, nil
}

// isPathSegment reports whether the name can be used as a single directory
// name under cue.mod/gen.
func isPathSegment(name string) bool {
	return name != "" && name != "." && name != ".." &&
		!strings.ContainsAny(name, `/\`)
}

// selectCRDs returns the CRDs matching the kind and version selectors.
// Kinds match either the Kind or the Kind.group name, case-insensitively.
// Versions are removed from the returned CRD objects when not selected.
// An error is returned when a selector is empty or matches nothing in the
// manifest, or when a selected kind is left without versions.
func selectCRDs(crds []crdEntry, kinds, versions []string, file string) ([]crdEntry, error) {
	kinds, err := trimSelectors(kinds, "kind")
	if err != nil {
		return nil, err
	}
	versions, err = trimSelectors(versions, "version")
	if err != nil {
		return nil, err
	}

	selected := crds
	if len(kinds) > 0 {
		selected = nil
		picked := make(map[int]bool)
		for _, kind := range kinds {
			found := false
			for i, crd := range crds {
				if !strings.EqualFold(kind, crd.kind) && !strings.EqualFold(kind, crd.name()) {
					continue
				}
				found = true
				if !picked[i] {
					picked[i] = true
					selected = append(selected, crd)
				}
			}
			if !found {
				return nil, fmt.Errorf("kind %q not found in %s, available kinds: %s",
					kind, file, strings.Join(crdNames(crds), ", "))
			}
		}
	}

	if len(versions) == 0 {
		return selected, nil
	}

	available := crdVersions(selected)
	for _, version := range versions {
		if !containsFold(available, version) {
			return nil, fmt.Errorf("version %q not found in %s for the selected kinds, available versions: %s",
				version, file, strings.Join(available, ", "))
		}
	}

	result := make([]crdEntry, 0, len(selected))
	for _, crd := range selected {
		filtered, err := filterCRDVersions(crd, versions)
		if err != nil {
			return nil, err
		}
		if len(filtered.versions) == 0 {
			return nil, fmt.Errorf("no versions selected for %s, available versions: %s",
				crd.name(), strings.Join(crd.versions, ", "))
		}
		result = append(result, filtered)
	}

	return result, nil
}

// trimSelectors returns the selector values without surrounding whitespace,
// failing when a value is empty.
func trimSelectors(values []string, flag string) ([]string, error) {
	out := make([]string, 0, len(values))
	for _, v := range values {
		v = strings.TrimSpace(v)
		if v == "" {
			return nil, fmt.Errorf("the %s selector must not be empty", flag)
		}
		out = append(out, v)
	}
	return out, nil
}

// filterCRDVersions returns a copy of the CRD with only the selected versions
// kept in the object's spec.versions list.
func filterCRDVersions(crd crdEntry, versions []string) (crdEntry, error) {
	object := crd.object.DeepCopy()
	list, _, _ := unstructured.NestedSlice(object.Object, "spec", "versions")

	filtered := crdEntry{kind: crd.kind, group: crd.group, object: object}
	var kept []any
	for _, v := range list {
		version, ok := v.(map[string]any)
		if !ok {
			continue
		}
		name, _ := version["name"].(string)
		if containsFold(versions, name) {
			kept = append(kept, v)
			filtered.versions = append(filtered.versions, name)
		}
	}

	if err := unstructured.SetNestedSlice(object.Object, kept, "spec", "versions"); err != nil {
		return crdEntry{}, fmt.Errorf("filtering versions of %s failed: %w", crd.name(), err)
	}

	return filtered, nil
}

// listCRDs prints a table with the Kind.group and version of each CRD.
func listCRDs(w io.Writer, crds []crdEntry) {
	var rows [][]string
	for _, crd := range crds {
		for _, version := range crd.versions {
			rows = append(rows, []string{crd.name(), version})
		}
	}
	sort.Slice(rows, func(i, j int) bool {
		if !strings.EqualFold(rows[i][0], rows[j][0]) {
			return lessFold(rows[i][0], rows[j][0])
		}
		return rows[i][1] < rows[j][1]
	})

	printTable(w, []string{"kind", "version"}, rows)
}

// pruneCRDs removes the vendored definitions found under the given API groups
// that were not generated by the current run. Only the files generated by
// timoni are removed, along with the version, kind and group directories
// left empty. Symbolic links are never followed.
func pruneCRDs(log logr.Logger, genDir string, groups []string, generated map[string][]byte) error {
	for _, group := range groups {
		groupDir := path.Join(genDir, group)
		if !isDirectory(groupDir) {
			continue
		}
		kinds, err := os.ReadDir(groupDir)
		if err != nil {
			return err
		}

		for _, kind := range kinds {
			if !kind.IsDir() {
				continue
			}
			kindDir := path.Join(groupDir, kind.Name())
			versions, err := os.ReadDir(kindDir)
			if err != nil {
				return err
			}

			for _, version := range versions {
				if !version.IsDir() {
					continue
				}
				key := path.Join(group, kind.Name(), version.Name())
				if _, ok := generated[key]; ok {
					continue
				}

				versionDir := path.Join(kindDir, version.Name())
				genFile := path.Join(versionDir, "types_gen.cue")
				if !isGeneratedByTimoni(genFile) {
					log.Info(fmt.Sprintf("schemas skipped: %s not generated by timoni", logger.ColorizeSubject(key)))
					continue
				}
				if err := os.Remove(genFile); err != nil {
					return err
				}
				log.Info(fmt.Sprintf("schemas pruned: %s", logger.ColorizeSubject(key)))

				if err := removeEmptyDir(versionDir); err != nil {
					return err
				}
			}

			if err := removeEmptyDir(kindDir); err != nil {
				return err
			}
		}

		if err := removeEmptyDir(groupDir); err != nil {
			return err
		}
	}

	return nil
}

// isDirectory reports whether the path is a directory and not a symbolic link.
func isDirectory(dir string) bool {
	fi, err := os.Lstat(dir)
	return err == nil && fi.IsDir()
}

// isGeneratedByTimoni reports whether the file starts with the generated code marker.
func isGeneratedByTimoni(file string) bool {
	if fi, err := os.Lstat(file); err != nil || !fi.Mode().IsRegular() {
		return false
	}
	f, err := os.Open(file)
	if err != nil {
		return false
	}
	defer f.Close()

	buf := make([]byte, len(generatedMarker))
	n, err := io.ReadFull(f, buf)
	if err != nil {
		return false
	}
	return string(buf[:n]) == generatedMarker
}

// removeEmptyDir removes the directory when it has no entries.
func removeEmptyDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	if len(entries) > 0 {
		return nil
	}
	return os.Remove(dir)
}

// crdGroups returns the sorted set of API groups of the given CRDs.
func crdGroups(crds []crdEntry) []string {
	seen := make(map[string]bool)
	var groups []string
	for _, crd := range crds {
		if !seen[crd.group] {
			seen[crd.group] = true
			groups = append(groups, crd.group)
		}
	}
	sort.Strings(groups)
	return groups
}

// crdNames returns the sorted Kind.group names of the given CRDs.
func crdNames(crds []crdEntry) []string {
	names := make([]string, 0, len(crds))
	for _, crd := range crds {
		names = append(names, crd.name())
	}
	sort.Slice(names, func(i, j int) bool { return lessFold(names[i], names[j]) })
	return names
}

// crdVersions returns the sorted set of versions defined by the given CRDs.
func crdVersions(crds []crdEntry) []string {
	seen := make(map[string]bool)
	var versions []string
	for _, crd := range crds {
		for _, version := range crd.versions {
			if !seen[version] {
				seen[version] = true
				versions = append(versions, version)
			}
		}
	}
	sort.Strings(versions)
	return versions
}

// lessFold reports whether a sorts before b, compared case-insensitively.
func lessFold(a, b string) bool {
	return strings.ToLower(a) < strings.ToLower(b)
}

// containsFold reports whether the list holds the value, compared case-insensitively.
func containsFold(values []string, value string) bool {
	for _, v := range values {
		if strings.EqualFold(v, value) {
			return true
		}
	}
	return false
}

// readRemoteCRDManifest downloads a response within the size limit without redirecting to HTTP.
func readRemoteCRDManifest(ctx context.Context, client *http.Client, url string, maxSize int64) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create HTTP request for %s, error: %w", url, err)
	}

	httpClient := *client
	checkRedirect := httpClient.CheckRedirect
	httpClient.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if req.URL.Scheme != "https" {
			return fmt.Errorf("redirect to insecure HTTP URL %s", req.URL)
		}
		if checkRedirect != nil {
			return checkRedirect(req, via)
		}
		if len(via) >= 10 {
			return fmt.Errorf("stopped after 10 redirects")
		}
		return nil
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to download manifest from %s, error: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("failed to download manifest from %s, status: %s", url, resp.Status)
	}
	if resp.ContentLength > maxSize {
		return nil, fmt.Errorf("failed to download manifest from %s, response exceeds the %d-byte limit", url, maxSize)
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, maxSize+1))
	if err != nil {
		return nil, fmt.Errorf("failed to download manifest from %s, error: %w", url, err)
	}
	if int64(len(data)) > maxSize {
		return nil, fmt.Errorf("failed to download manifest from %s, response exceeds the %d-byte limit", url, maxSize)
	}

	return data, nil
}
